# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version:  14.x
        
    - name: Install environment Angular
      run: npm install @angular/cli@9.1.12
      
    - name: Build
      run: ng build --prod
    
    - name: Unit tests
      run: ng test --browsers ChromeHeadless

    - name: Publish Artifact
      uses: actions/upload-artifact@v2.1.3
      with:
        # Artifact name
        name: WebApp
        # A file, directory or wildcard pattern that describes what to upload
        path: ./dist/estudo-github-actions
