# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Build Source
      uses: actions/checkout@v1
      
    - name: Set Base Enviromnent
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
        
    - name: Pre-build
      run: | 
        npm install
        npm run lint
      
    - name: Build
      run: npm run build -- --prod
      
    - name: Test
      run: |
        npm run test:ci
        npm run e2e
        
    - name: Semantic release
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx semantic-release
